# Generated by Django 4.2 on 2025-06-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('estaPago', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'Recibos',
            },
        ),
    ]
