# Generated by Django 4.2 on 2025-06-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recibos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='tenantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recibos', to=settings.AUTH_USER_MODEL),
        ),
    ]
