# Generated by Django 4.2 on 2025-06-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=250)),
                ('emailCliente', models.EmailField(max_length=100)),
                ('telefonoCliente', models.CharField(blank=True, max_length=45, null=True)),
                ('cedulaCliente', models.CharField(max_length=45, null=True)),
                ('fechaDeAsignacion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En transito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pending', max_length=16)),
                ('trackingNumber', models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True)),
                ('empresaOrigen', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedidos',
            },
        ),
    ]
