# Generated by Django 4.2 on 2025-06-13 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0001_initial'),
        ('Zonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cadeteId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pedidos_Asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='zonaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='Zonas.zona'),
        ),
    ]
