# Generated by Django 4.2 on 2025-06-13 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='adminId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='tenantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
