# Generated by Django 4.2 on 2025-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='foto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
