# Generated by Django 4.2 on 2025-06-09 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sucursales', '0003_alter_sucursal_options_alter_sucursal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='adminId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
