# Generated by Django 4.2 on 2025-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0004_alter_sucursal_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='sucursales/'),
        ),
    ]
