# Generated by Django 4.2 on 2025-06-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firmaDelReceptor', models.CharField(max_length=50)),
                ('fechaDeEntrega', models.DateTimeField(auto_now=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'Entregas',
            },
        ),
    ]
