# Generated by Django 4.2 on 2025-06-12 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zonas', '0001_initial'),
        ('Sucursales', '0005_alter_sucursal_foto'),
        ('Usuarios', '0002_alter_usuario_email_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sucursales.sucursal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tenantId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Zonas.zona'),
        ),
    ]
