# Generated by Django 4.2 on 2025-06-13 23:40

import Usuarios.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', Usuarios.managers.UsuarioManager()),
            ],
        ),
    ]
