# Generated by Django 4.2 on 2025-06-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuario_sucursal_usuario_tenantid_usuario_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super_Administrador'), ('adminSucursal', 'Administrador_De_Sucursal'), ('cadete', 'Cadete'), ('tenant', 'Tenant')], max_length=50),
        ),
    ]
